const group_1 = [
  // "Công cha như núi Thái Sơn, nghĩa mẹ như nước trong nguồn chảy ra.",
  // "Anh em như thể tay chân, rách lành đùm bọc dở hay đỡ đần.",
  // "Một giọt máu đào hơn ao nước lã.",
  // "Chị ngã em nâng.",
  // "Môi hở răng lạnh.",
  // "Con dại cái mang.",
  // "Cá không ăn muối cá ươn, con cãi cha mẹ trăm đường con hư.",
  // "Công cha nghĩa mẹ ơn thầy, ngày sau khôn lớn ơn dày biển sâu.",
  // "Con hơn cha là nhà có phúc.",
  // "Dạy con từ thuở còn thơ, dạy vợ từ thuở bơ vơ mới về.",
  // "Chim có tổ, người có tông; như cây có cội, như sông có nguồn.",
  // "Một mẹ già bằng ba nhà ruộng.",
  // "Khôn ngoan đối đáp người ngoài, gà cùng một mẹ chớ hoài đá nhau.",
  // "Máu chảy ruột mềm.",
  // "Lên non mới biết non cao, nuôi con mới biết công lao mẫu từ.",
  "Công cha như núi Thái Sơn, nghĩa mẹ như nước trong nguồn chảy ra.",
  "Con có cha như nhà có nóc.",
  "Anh em như thể tay chân, rách lành đùm bọc dở hay đỡ đần.",
  "Một giọt máu đào hơn ao nước lã.",
  "Con người có tổ có tông, như cây có cội như sông có nguồn.",
  "Cháu bà nội, tội bà ngoại.",
  "Cá không ăn muối cá ươn, con cưỡng cha mẹ trăm đường con hư.",
  "Khôn ngoan đối đáp người ngoài, gà cùng một mẹ chớ hoài đá nhau.",
  "Chị ngã em nâng.",
  "Công cha nghĩa mẹ ơn thầy.",
  "Cắt dây bầu dây bí, ai nỡ cắt dây chị dây em.",
  "Mẹ nuôi con bằng trời bằng bể, con nuôi mẹ kể tháng kể ngày.",
  "Sảy cha còn chú, sảy mẹ bú dì.",
  "Ngó lên nuộc lạt mái nhà, bao nhiêu nuộc lạt nhớ bà bấy nhiêu.",
  "Ơn đức cha mẹ cao như núi, dài như sông.",
]; // Về tình cảm Gia đình & Hiếu đạo

const group_2 = [
  // "Có công mài sắt, có ngày nên kim.",
  // "Học thầy không tày học bạn.",
  // "Đi một ngày đàng, học một sàng khôn.",
  // "Tiên học lễ, hậu học văn.",
  // "Dốt đến đâu học lâu cũng biết.",
  // "Không thầy đố mày làm nên.",
  // "Lửa thử vàng, gian nan thử sức.",
  // "Thất bại là mẹ thành công.",
  // "Học ăn, học nói, học gói, học mở.",
  // "Muốn biết phải hỏi, muốn giỏi phải học.",
  // "Văn ôn võ luyện.",
  // "Có chí thì nên.",
  // "Chớ thấy sóng cả mà ngã tay chèo.",
  // "Thua keo này, bày keo khác.",
  
  // "Học thầy không tày học bạn.",
  "Đi một ngày đàng, học một sàng khôn.",
  "Tiên học lễ, hậu học văn.",
  "Học ăn, học nói, học gói, học mở.",
  "Muốn biết phải hỏi, muốn giỏi phải học.",
  "Văn ôn võ luyện.",
  "Học đi đôi với hành.",
  "Dốt đến đâu học lâu cũng biết.",
  "Sách là kho tàng tri thức.",
  "Không thầy đố mày làm nên.",
  "Một kho vàng không bằng một nang chữ.",
  "Ngọc không mài không sáng, người không học không hiểu lý.",
  "Học là học để làm người.",
  "Chớ thấy sóng cả mà ngã tay chèo.",
  "Cần cù bù thông minh.",
  "Nước chảy đá mòn.",
]; //Về Học tập & Ý chí rèn luyện

const group_3 = [
  // "Chuồn chuồn bay thấp thì mưa, bay cao thì nắng, bay vừa thì râm.",
  // "Nhất nước, nhì phân, tam cần, tứ giống.",
  // "Tốt gỗ hơn tốt nước sơn.",
  // "Tháng bảy kiến bò, chỉ lo lại lụt.",
  // "Đêm tháng năm chưa nằm đã sáng, ngày tháng mười chưa cười đã tối.",
  // "Mau sao thì nắng, vắng sao thì mưa.",
  // "Khoai đất lạ, mạ đất quen.",
  // "Nắng tốt dưa, mưa tốt lúa.",
  // "Chớp đông nhay nháy, gà gáy thì mưa.",
  // "Trăm hay không bằng tay quen.",
  // "Lúa chiêm lấp ló đầu bờ, hễ nghe tiếng sấm phất cờ mà lên.",
  // "Được mùa chớ phụ ngô khoai, đến khi thất bát lấy ai bạn cùng.",
  // "Nhai kĩ no lâu, cày sâu tốt lúa.",
  // "Ráng mỡ gà, có nhà thì giữ.",
  // "Nước đến chân mới nhảy.",
  "Có công mài sắt, có ngày nên kim.",
  "Lúa chiêm lấp ló đầu bờ, hễ nghe tiếng sấm phất cờ mà lên.",
  "Kiến tha lâu đầy tổ.",
  "Thất bại là mẹ thành công.",
  "Lửa thử vàng, gian nan thử sức.",
  "Có chí thì nên.",
  "Nước chảy đá mòn.",
  "Tay làm hàm nhai, tay quai miệng trễ.",
  "Muốn ăn thì lăn vào bếp.",
  "Tấc đất tấc vàng.",
  "Khoai đất lạ, mạ đất quen.",
  "Được mùa chớ phụ ngô khoai, đến khi thất bát lấy ai bạn cùng.",
  "Một lần ngại tốn, bốn lần chẳng xong.",
  "Làm ruộng ba năm không bằng chăn tằm một lứa.",
  "Thức khuya dậy sớm.",
]; //Về Kinh nghiệm sản xuất & Thời tiết

const group_4 = [
  // "Ở hiền gặp lành.",
  // "Uống nước nhớ nguồn.",
  // "Ăn quả nhớ kẻ trồng cây.",
  // "Thương người như thể thương thân.",
  // "Lá lành đùm lá rách.",
  // "Đói cho sạch, rách cho thơm.",
  // "Giấy rách phải giữ lấy lề.",
  // "Cây ngay không sợ chết đứng.",
  // "Một miếng khi đói bằng một gói khi no.",
  // "Lời nói gói vàng.",
  // "Ăn ngay nói thật, mọi tật mọi lành.",
  // "Gieo gió gặt bão.",
  // "Ác giả ác báo.",
  // "Sông có khúc, người có lúc.",
  // "Cười người hôm trước, hôm sau người cười.",
  "Lá lành đùm lá rách.",
  "Bầu ơi thương lấy bí cùng, tuy rằng khác giống nhưng chung một giàn.",
  "Một con ngựa đau, cả tàu bỏ cỏ.",
  "Thương người như thể thương thân.",
  "Uống nước nhớ nguồn.",
  "Ăn quả nhớ kẻ trồng cây.",
  "Đói cho sạch, rách cho thơm.",
  "Giấy rách phải giữ lấy lề.",
  "Lời nói chẳng mất tiền mua, lựa lời mà nói cho vừa lòng nhau.",
  "Ở hiền gặp lành.",
  "Gần mực thì đen, gần đèn thì rạng.",
  "Trọng nghĩa khinh tài.",
  "Một sự nhịn là chín sự lành.",
  "Nhập gia tùy tục.",
  "Tôn sư trọng đạo.",
]; //Về Đạo đức & Nhân cách sống

const group_5 = [
  "Bán anh em xa, mua láng giềng gần.",
  "Lời chào cao hơn mâm cỗ.",
  "Một sự nhịn, chín sự lành.",
  "Lời nói chẳng mất tiền mua, lựa lời mà nói cho vừa lòng nhau.",
  "Biết người biết ta, trăm trận trăm thắng.",
  "Ăn cỗ đi trước, lội nước theo sau.",
  "Tránh vỏ dưa, gặp vỏ dừa.",
  "Gần mực thì đen, gần đèn thì rạng.",
  "Ở bầu thì tròn, ở ống thì dài.",
  "Đi với bụt mặc áo cà sa, đi với ma mặc áo giấy.",
  "Giàu vì bạn, sang vì vợ.",
  "Chọn bạn mà chơi, chọn nơi mà ở.",
  "Đèn nhà ai nấy rạng.",
  "Cái răng cái tóc là góc con người.",
  "Im lặng là vàng.",
]; //Về Ứng xử xã hội & Đối nhân xử thế

const group_6 = [
  // "Chưa đỗ ông nghè đã đe hàng tổng.",
  // "Ếch ngồi đáy giếng.",
  // "Thùng rỗng kêu to.",
  // "Vừa ăn cướp, vừa la làng.",
  // "Mèo khen mèo dài đuôi.",
  // "Chó chê mèo lắm lông.",
  // "Cầm đèn chạy trước ô tô.",
  // "Ăn cháo đá bát.",
  // "Qua cầu rút ván.",
  // "Miệng nam mô, bụng bồ dao găm.",
  // "Đàn gảy tai trâu.",
  // "Việc nhà thì nhác, việc chú bác thì siêng.",
  // "Mật ngọt chết ruồi.",
  // "Ngựa non háu đá.",
  // "Treo đầu dê, bán thịt chó.",
  'Tốt gỗ hơn tốt nước sơn.',
  "Cái nết đánh chết cái đẹp.",
  "Thẳng như ruột ngựa.",
  "Qua cầu rút ván.",
  "Vắng chủ nhà gà vọc niêu tôm.",
  "Cưỡi ngựa xem hoa.",
  "Thùng rỗng kêu to.",
  "Đứng núi này trông núi nọ.",
  "Miệng nam mô, bụng bồ dao găm.",
  "Sông có khúc, người có lúc.",
  "Biết người biết ta, trăm trận trăm thắng.",
  "Thắng không kiêu, bại không nản.",
  "Khẩu xà tâm phật.",
  "Tẩm ngẩm tầm ngầm mà đấm chết voi.",
  "Ăn ít no lâu, ăn nhiều chóng đói.",
]; //Phê phán thói hư tật xấu (Châm biếm)
